### PR TITLE
Dynamically Running Embedded Scripts

### PR DESCRIPTION
**Pull request by Martin-Alexander**
Dynamically load script tags after post is rendered & removed code specific to rendering embedded tweets.

This solution dynamically fetches third-party code.

Unfortunately, some third-party resources are protected from being fetched/run in this fashion (by [CORS](https://en.wikipedia.org/wiki/Cross-origin_resource_sharing)). So, if this occurs the code will attempt to use a third-party proxy server called [CORS Anywhere ](https://github.com/Rob--W/cors-anywhere) to bypass this.

If ever this free service goes offline or is down then some embedded content will not load properly.

To prevent this from ever happening we'd need to run/host this reverse proxy server ourselves.

### CODE REVIEW

**Comment by Martin-Alexander** [comment]
I'm not very confident with this solution since it's relying on a free third-party server that is essentially just a demo. But unless you want to host your own server (the code is open source) then I can't think of a different way.

I don't know what percentage of embedded widgets use code that is "protected" behind a CORS policy...

**Comment by mattbischoff** [comment]
This makes me think maybe we should give up on the auto-scrolling and just do manual pagination. Would that solve the issue?

**Comment by Martin-Alexander** [comment]
That would solve this issue. Yes.

One thing to consider:

This problem of dynamically loading third party widgets/embeds also applies to switching categories & years. If you notice, when switching categories: the page doesn't reload, rather the posts just appear (they're loaded dynamically). 

Would you like me to also change the behaviour of the category & year buttons to reload the page?

**Comment by Martin-Alexander** [comment]
Another thing that might currently be affected by this issue:

Having the "Read more" button expand a post might also cause this issue. Because the content below the "Read more" is not initially rendered, some widgets/embeds might not be properly loaded when they are revealed.

I just thought of this now, and I don't know if it's actually presently an issue with any post. But I can look into this as well.

**Comment by mattbischoff** [comment]
> This problem of dynamically loading third party widgets/embeds also applies to switching categories & years. If you notice, when switching categories: the page doesn't reload, rather the posts just appear (they're loaded dynamically).

Would you like me to also change the behaviour of the category & year buttons to reload the page?

Yeah. I’m fine with a page reload there also.

**Comment by mattbischoff** [comment]
> I just thought of this now, and I don't know if it's actually presently an issue with any post. But I can look into this as well.

Thanks. if that also needs to become a permalink instead, that’s fine.

**Pull request closed without merging**
